### ISSUE TITLE
Add pip requirements.txt

### ISSUE THREAD

**Issue by Metallicow** [driscollis/boomslang#1]
[Woooooooooooooooooooot First Issue!](https://pip.pypa.io/en/stable/user_guide/#requirements-files)

...other than that everything started just fine. lxml no names.

**Comment by shanerigby** [comment]
PyPubSub seems to be an undocumented pre-requisite (very minor I know).

**Comment by driscollis** [comment]
@Metallicow Sorry for not getting to this. I just added a file

**Comment by driscollis** [comment]
@shanerigby Thanks! I added a **requirements.txt** file. I'll also update the readme
